### ISSUE TITLE
crypto: invalid key length

### ISSUE THREAD

**Issue by colorzzr** [minio/kes#126]
#### Bug describtion

Hi I am try to connect MinIO with kes. I followed this https://github.com/minio/kes/wiki/MinIO-Object-Storage. afterwards, I try to upload a file to encryption bucket. MinIO reports following error:

```
API: SYSTEM()
Time: 10:05:49 EDT 05/13/2021
DeploymentID: 71c29374-7d66-428e-8b58-3b65d54289c7
Error: crypto: invalid key length (*errors.errorString)
       6: cmd/logger/logger.go:394:logger.CriticalIf()
       5: cmd/crypto/key.go:48:crypto.GenerateKey()
       4: cmd/encryption-v1.go:249:cmd.newEncryptMetadata()
       3: cmd/encryption-v1.go:264:cmd.newEncryptReader()
       2: cmd/encryption-v1.go:331:cmd.EncryptRequest()
       1: cmd/web-handlers.go:1279:cmd.(*webAPIHandlers).Upload()
```

I check the code at `cmd/crypto/key.go:48` in minio repo. It seem like it require 32 byte key, the key I generated is 64 byte. Is there any way to solve this issue? Thanks!

#### Expected behavior

File can be upload without any error.

#### Additional context

None

**Comment by aead** [comment]
@colorzzr This behavior is caused by a bug in the MinIO server. The following PR fixes this https://github.com/minio/minio/pull/12290

However, you're seeing this behavior because the `GenerateKey` function fails. So, your current KES integration is not working properly.

Ideally, check that `kes key derive -k <your-key-name>` succeeds.

**Comment by colorzzr** [comment]
@aead Thanks for quick response. I check the `kes key derive -k <your-key-name>` with my key. It successfully returns following

```
./kes key derive -k my-minio-key
{
  plaintext : wppnWffG5p1SzWNN3+T3jQ2c9Ego2jG5eZPVGXJcm+4=
  ciphertext: eyJhZWFkIjoiQUVTLTI1Ni1HQ00tSE1BQy1TSEEtMjU2IiwiaXYiOiJTQTFzL2MrZHl4K2NQTXU5MWdBelpnPT0iLCJub25jZSI6IlAzVmR0V3FjM0ppM2dOb1UiLCJieXRlcyI6InlqMXhNUUNTK3lPeEx1RFRYNTRBY2JIOXhJNUFzZ2FRdHVPcVBxK09yRjcyNzZCTDMxYUYrN0xRZjVjeXVUUlYifQ==
}
```

**Comment by aead** [comment]
Okay, based on that you should be able to upload an object on a bucket that has a SSE-S3 configuration.
The `Error: crypto: invalid key length (*errors.errorString)` should only happen when MinIO fails to communicate to KES.
Once the PR mentioned above is merged MinIO should return a more descriptive error message.

**Comment by colorzzr** [comment]
Thanks!
