### ISSUE TITLE
Document how to retain data/keys in docker image

### ISSUE THREAD

**Issue by zefie** [minio/kes#133]
#### What is the problem you want to solve?

Used KES with Minio, uploaded all my data, after docker restart the data is inaccessible and the key is gone.

#### How do you want to solve it?
I have a backup of the plaintext and ciphertext if I can somehow manually create a key, but it would still rely on knowing which folder to export as a volume in docker, which is not documented that I could find.

#### Additional context
Update: Apparently my config was missing the "keystore:" section. I had configured vault: but not "keystore:" Perhaps throw an error when misconfigured.

**Comment by aead** [comment]
See: https://github.com/minio/kes/wiki/Getting-Started

> Here we show how to setup a local KES server that stores keys in-memory. Therefore, all keys will be gone once the KES server has been shut down.

The KES Server will print the connected key store on startup.

![Screenshot 2021-06-21 at 22 50 41](https://user-images.githubusercontent.com/20368805/122826399-5e833b80-d2e3-11eb-89e1-1ba84570646e.png)
