### ISSUE TITLE
Make the server public API

### ISSUE THREAD

**Issue by toby3d** [minio/kes#164]
#### What is the problem you want to solve?

I want to test connections to the KES InMemory server without install/running binary manually but directly in Go code. Unfortunately, due to the closed API of the server I have to resort to not the most reliable methods of running the server via `os/exec`, which makes testing more fragile than I would like. It would be nice to provide a public server API that can be initialized, configured and managed directly from the source code, without installing a binary.

#### How do you want to solve it?

Create a public server entity with a set of some options and provide the ability to use it. Or rearrange existing methods in [cmd/server.go](https://github.com/minio/kes/blob/master/cmd/kes/server.go) to use them externally. Maybe you can limit instantiation to InMemory storage only, that's enough for tests with short-lived data.

#### Additional context

1. Are there alternative solutions?
For now, I limit myself to the following utility to initialize the server on a random port and return a client connected to it and the function for `testing.Cleanup`:
```go
//go:generate kes tool identity new --force --server --key server.key --cert server.cert --ip "127.0.0.1" --dns localhost
//go:generate kes tool identity new --force --key=root.key --cert=root.cert root
package util

import (
	"bufio"
	"crypto/tls"
	"net"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/minio/kes"
	"github.com/stretchr/testify/require"
)

// TestKES returns prepared KES Client connected to in-memory KES server and Cleanup function.
func TestKES(tb testing.TB) (*kes.Client, func()) {
	tb.Helper()

	require := require.New(tb)

	// NOTE(toby3d): load testing self-signed certificates
	rootCert := filepath.Join(".", "root.cert")
	rootKey := filepath.Join(".", "root.key")
	certPath := filepath.Join(".", "server.cert")
	keyPath := filepath.Join(".", "server.key")

	cert, err := tls.LoadX509KeyPair(rootCert, rootKey)
	require.NoError(err)

	// WARN(toby3d): this is not OK, but it works now
	identity, err := exec.Command("kes", "tool", "identity", "of", rootCert).Output()
	require.NoError(err)

	// NOTE(toby3d): use any open port for server instance
	l, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(err)

	addr := l.Addr().String()
	require.NoError(l.Close())

	// WARN(toby3d): run server via installed minio/kes binary
	cmdServer := exec.Command(
		"kes", "server",
		"--key="+keyPath,
		"--cert="+certPath,
		"--root="+string(identity),
		"--auth=off",
		"--addr="+addr,
	)

	// NOTE(toby3d): "dirty" way to wait for the server to start:
	// after starting the utility displays in StdOut information
	// about the address to connect clients. At the moment
	// the message occurs, we stop reading the channel
	// and connect the client to it.

	stdout, err := cmdServer.StdoutPipe()
	require.NoError(err)
	defer stdout.Close()

	require.NoError(cmdServer.Start())

	scanner := bufio.NewScanner(stdout)
	for scanner.Scan() {
		// WARN(toby3d): there is always a risk that the wrong
		// thing will arrive at StdOut and all further logic will
		// fall apart. But time.Sleep is too fragile, and there are
		// no other relatively reliable ways. 
		break
	}

	// NOTE(toby3d): create a client connected to a (sort of) fully prepared server
	client := kes.NewClientWithConfig("https://"+addr, &tls.Config{
		Certificates: []tls.Certificate{cert},
		// WARN(toby3d): only for self-signed certificates as part of testing
		InsecureSkipVerify: true,
	})

	return client, func() {
		cmdServer.Process.Kill()
	}
}
```
In the most tests it is applied in the following way:
```go
package example_test

import (
	"testing"
	"example"
)

func TestSomething(t *testing.T) {
	t.Parallel()
	
	client, cleanup := example.TestKES(t)
	t.Cleanup(cleanup)
	
	// TODO(toby3d): use a fully prepared KES client according to its API
}
```
2. Would your solution cause a major breaking API change?
This involves adding methods and entities to the existing API, so I don't think it should break existing clients.
3. Anything else that is important?
No, maybe?

**Comment by toby3d** [comment]
> How hard it is to run Kes locally?

In my opinion, `go test` should do all the work itself, without requiring the developer to run and install third-party solutions. The more steps required just to start build/test, the more unnecessary dependencies and the higher the entry threshold for new developers.

**Comment by klauspost** [comment]
Seems like a reasonable request to me. 

Though `go run github.com/minio/kes/cmd/kes@latest ...` in a `TestMain(M *testing.M)` is also a fairly reliable crossplatform way to start it, running it as a compiled in-method will be more relaiable.
