### ISSUE TITLE
New KES in Minio Tenant

### ISSUE THREAD

**Issue by antony14110** [minio/kes#175]
Hello,

Knowing that I use for my development servers a Minio tenant with 2 pods and 4 disks (2 on each). Configuration with Minio Operator is not possible (apparently it requires 4 servers). This is what I used the solution for with the Minio pluggoin.
Is it possible to add a Gemalto compatible Minio-KES server in an existing Minio tenant?
If so, what is the command line? (I can't find much information on the subject).

Thank's

**Comment by aead** [comment]
> Is it possible to add a Gemalto compatible Minio-KES server in an existing Minio tenant?

Yes, however you need to configure all MinIO nodes of that tenant to talk to one/multiple KES servers connected to the Gemalto KeySecure / CipherTrust Manager. See: https://github.com/minio/kes/wiki/Gemalto-KeySecure

**Comment by aead** [comment]
Closing this as answered. Reopen otherwise.
