### ISSUE TITLE
[kes + minio] Error: no admin identity specified

### ISSUE THREAD

**Issue by iamazeem** [minio/kes#185]
#### Bug describtion

Tried to set up `kes` for `minio` by following the steps listed here:

- https://github.com/minio/kes/wiki/MinIO-Object-Storage

In the [sample config](https://github.com/minio/kes/wiki/MinIO-Object-Storage#3-now-we-have-defined-all-entities-in-our-demo-setup), the `root` has been disabled:

```yaml
root:    disabled  # We disable the root identity since we don't need it in this guide
```

Starting `kes server` generated the following error:

```bash
$ kes server --config=server-config.yml --auth=off
Error: no admin identity specified
```

Originated from:

https://github.com/minio/kes/blob/4073c5f0643d437c3f488157667ae1c1cb343f14/cmd/kes/server.go#L129-L131

Had to generate and configure the root identity under `admin: itdentity` with:

- https://github.com/minio/kes/wiki/Getting-Started#22-create-the-root-identity
- https://github.com/minio/kes/wiki/Getting-Started#23-server-configuration

And, then it worked fine.

#### Expected behavior

Expected the `kes server` to run without the root identity as mentioned in the [MinIO Object Storage](https://github.com/minio/kes/wiki/MinIO-Object-Storage) tutorial.

Please take a look at it.
Maybe, the code needs to be fixed or the documentation needs updates accordingly.

#### Additional context

OS: Ubuntu 20.04
`kes` version: 0.17.6

**Comment by aead** [comment]
@iamazeem This is a bug in the `MinIO Object Storage` guide. I've updated the guide to contain a valid config snippet.
Thanks for reporting this.

**Comment by stoffeastrom** [comment]
@aead Seems like https://github.com/minio/kes/wiki/Getting-Started#2-setup-the-server is not updated as well. This references `kes tool` which seems to be removed. Trying to upgrade to `v0.18.0` and just realised that `tool` is removed.

**Comment by aead** [comment]
@stoffeastrom Thanks, updated getting started guide.
