### ISSUE TITLE
not authorized: insufficient permissions

### ISSUE THREAD

**Issue by 597800451** [minio/kes#227]
root@:/opt/webapps/kes/kes-conf#  kes key create my-key-1 -k
Error: failed to create key "my-key-1": not authorized: insufficient permissions

![image](https://user-images.githubusercontent.com/5043738/163515107-bce9a0a0-f07c-4ad6-a3ec-9d7a8adc3822.png)

**Comment by aead** [comment]
Your client identity (certificate) does not have sufficient permissions to list keys.
In particular, your policy does not allow: [`List Key`](https://github.com/minio/kes/wiki/Server-API#List-Keys)

The policy in your server configuration file has to be adjusted to include this API.
