### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by skitsanos** [minio/kes#250]
Suddenly started having this error.
```
Error: Post "https://kes-server:7373/v1/key/decrypt/minio-storage-kms-key": x509: certificate has expired or is not yet valid: current time 2022-07-02T09:23:13Z is after 2022-07-01T09:45:45Z (*url.Error)
```

It used to work for a few months since Kes was introduced, without any issues.

What could that be? and why now?

**Comment by harshavardhana** [comment]
@skitsanos your cert has expired, please renew it.

**Comment by skitsanos** [comment]
For how long is the certificate created by default with Kes?

**Comment by harshavardhana** [comment]
> For how long is the certificate created by default with Kes?

openssl x509 -enddate -noout -in <server.crt>

**Comment by skitsanos** [comment]
So Kes generates certificates for 30 days only.

```shell
kes identity new --ip "127.0.0.1" localhost
openssl x509 -enddate -noout -in public.crt
```

So I need to recreate certificates every 30 days, restart Kes, and restart MinIO as well, that's the flow? 

Why all these tiny details are never documented?

**Comment by harshavardhana** [comment]
@skitsanos what kes provides is a helper mechanism for client certs, we do not expect that you put those in production.  You should generate relevant client certs from your org cert generators that can provide you with relevant expiry. 

NOTE: if you ever read the --help it is documented

```
./kes identity new -h
Usage:
    kes identity new [options] <subject>

Options:
    --key <PATH>             Path to private key. (default: ./private.key) 
    --cert <PATH>            Path to certificate. (default: ./public.crt)
    -f, --force              Overwrite an existing private key and/or certificate.

    --ip <IP>                Add <IP> as subject alternative name. (SAN)
    --dns <DOMAIN>           Add <DOMAIN> as subject alternative name. (SAN)
    --expiry <DURATION>      Duration until the certificate expires. (default: 720h)
    --encrypt                Encrypt the private key with a password.

    -h, --help               Print command line options.
```

**Comment by skitsanos** [comment]
Thank you! Exactly this was missing from the docs. Appreciate you cleared it up.
