### ISSUE TITLE
aws kms does not use ec2 instance role

### ISSUE THREAD

**Issue by ericraymond** [minio/kes#26]
#### Bug description

Create a configuration for AWS KMS that does not specify an access_key, secret_key, or session_token.

#### Expected behavior

KES should use the ec2-instance role's credentials.  The AWS SDK  supports this if you use th default provider.

**Comment by aead** [comment]
The AWS client loads the configuration in the following order:
```
Environment Variables
Shared Credentials file
EC2 Instance Metadata (credentials only)
```
Therefore, it should fetch the EC2 instance credentials from: `http://169.254.169.254/latest/api/token` 
Can you elaborate more about what you try to achieve and what / why it's not working?

**Comment by harshavardhana** [comment]
Most probably one of the first two options has been true.. @aead

**Comment by aead** [comment]
@ericraymond PR #27 Fixes this bug. For deploying KES on an EC2 instance and using IAM roles just do not set the credentials in the config file. The KES server will automatically fetch the temp. credentials from the EC2 metadata.

**Comment by ericraymond** [comment]
Thanks! @aead
