### ISSUE TITLE
KMS type returns undefined on server startup after version 21.1

### ISSUE THREAD

**Issue by NellicusLabs** [minio/kes#314]
#### Bug describtion
Watching the logs the KMS version no longer shows the proper vault option at server startup in KMS versions >21.1. 
`KMS        undefined: undefined`

#### Expected behavior
Display proper KMS type / Domain
`KMS        Hashicorp Vault: https://vault.test.example
`
It does not appear to affect functionality at this time when using HashiCorp Vault

**Comment by aead** [comment]
@NellicusLabs Thanks for the bug report. This issue is already fixed in master and will be resolved for the next release.
I can confirm it only affects the terminal UI output and has no functional impact.
