### ISSUE TITLE
Is https://play.min.io:7373 down?

### ISSUE THREAD

**Issue by jeantanzj** [minio/kes#320]
#### Bug describtion

From the read me, this line should generate a key, but results in `curl: (7) Failed to connect to play.min.io port 7373 after 185 ms: Connection refused`
```
curl -sSL --tlsv1.3 \
    --key root.key \
    --cert root.cert \
    --data '{}' \
    -X POST 'https://play.min.io:7373/v1/key/generate/my-key'
```
#### Expected behavior

Successfully generate a key
#### Additional context

1. What version of Go are you using (`go version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. Anything else that is important?

**Comment by harshavardhana** [comment]
Yes it is down

**Comment by aead** [comment]
@jeantanzj We are working on bringing it back up again. Will update the issue once it's back.
