### ISSUE TITLE
Execute according to official documentation, error is reported: tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by xulongZheng** [minio/kes#343]
Ask for help

![1679666416449](https://user-images.githubusercontent.com/93906456/227541803-41d9709e-fb39-4ebc-af79-abe4b1dd3100.jpg)
@donatello @ymchun 
![未命名1679666506](https://user-images.githubusercontent.com/93906456/227542155-b3762bc5-74f1-4cfc-b4f7-058c9702824a.png)

**Comment by aead** [comment]
@xulongZheng If you read the line below:
> If you are running KES locally for testing purpose use `-k` or `--insecure` flag to create a key

You are running your KES server with a self-signed certificate.
Hence, specify `-k` to skip TLS certificate verification.
