### ISSUE TITLE
kes identity new: Missing Key usage 

### ISSUE THREAD

**Issue by Nowheresly** [minio/kes#344]
#### Bug describtion
The certificate generated by kes by using `kes identity new` command has changed.
With kes 0.22.3 and older, the `X509v3 Extended Key Usage` contains both `TLS Web Server Authentication, TLS Web Client Authentication`
Starting with kes version `2023-02-15T14-54-37Z`, the X509v3 Extended Key Usage` contains only `TLS Web Client Authentication`

As such, `kes identity new` cannot be used anymore to generate TLS certificate for kes. It ends up with this error

`remote error: tls: bad certificate`

#### Expected behavior

We expect `kes identity new` to generate certificate with `TLS Web Client Authentication` key usage

#### Additional context

This is how to reproduce the problem.

Use kes version 0.22.3 and enter the following commands:

```
./kes_0223 identity new  --expiry 8760h --dns kes --key kes_server223.key --cert kes_server223.crt kes
openssl x509 -noout -text -in kes_server223.crt
```

The ouput displayed by the openssl command shows:
```
 X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication

```

Now use the version `2023-02-15T14-54-37Z` of kes

```
./kes_latest identity new  --expiry 8760h --dns kes --key kes_server223.key --cert kes_serverlatest.crt kes
openssl x509 -noout -text -in kes_serverlatest.crt
```
The ouput of the openssl command is like this one:

```
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication

```

As a consequence, the generated certificate cannot be used for TLS

**Comment by aead** [comment]
@Nowheresly This issue is already fixed upstream. Ref: https://github.com/minio/kes/blob/599c467077c0f4e168bb926bf8c16825cb1c64a3/cmd/kes/identity.go#L164

Thank you for opening this issue.
