### ISSUE TITLE
Regression: Vault log spam

### ISSUE THREAD

**Issue by dhess** [minio/kes#398]
#### Bug describtion

Once per minute, per Kes instance, Kes generates the following log spam in Vault:

```
{"@level":"info","@message":"http: TLS handshake error from 10.20.3.20:48816: EOF","@timestamp":"2023-10-02T18:27:23.366012Z"}
```

Everything else is working fine &mdash; Kes is able to get keys from Vault.

This appears to be a regression to #230.

#### Expected behavior

No Vault log spam.

#### Additional context

MinIO is installed in our Kubernetes cluster via the `operator` and `tenant` Helm charts, v5.0.9. The Vault service is in the same cluster and using the `vault-active` service with the KV v2 engine and Kubernetes auth.

**Comment by Nowheresly** [comment]
We experience the same spam behavior.

**Comment by zveinn** [comment]
There was a big refactor of the internals of this repository a few days ago: https://github.com/minio/kes/commit/0e49f95c93318a32c2c49ee996449ee5cb5ce534

Please test the latest release and let us know if this spam still persists.
