### ISSUE TITLE
add support for any KMIP-compatible KMS

### ISSUE THREAD

**Issue by aead** [minio/kes#4]
The [KMIP protocol](https://en.wikipedia.org/wiki/Key_Management_Interoperability_Protocol) is a generic and extendable protocol for unifying the interaction between different KMS implementations and clients. The OASIS specification can be found [here](https://docs.oasis-open.org/kmip/kmip-spec/v2.0/os/kmip-spec-v2.0-os.html)
In general, kes seems to require a client implementation of three operations:
 - create
 - get
 - destroy  

However, before doing this I want to understand the KMIP protocol and standard in more detail. For instance there is a v2.0. So, is there an available (and used) v1.x? What exactly are the best practices vs. real world deployments? etc.
In general, I only want to add what is needed and makes sense. I want to avoid too many configuration nobs for exotic features (KMIP seems a broad standard) - since that will escalate quickly and lead to messy configuration...

**Comment by harshavardhana** [comment]
@aead we can close this with our reasonings?

**Comment by aead** [comment]
Closing this as currently out of scope. However, if the requirement comes up again we can reopen / revisit.
