### ISSUE TITLE
quay.io/minio/kes:latest is outdated

### ISSUE THREAD

**Issue by avoidik** [minio/kes#493]
#### What is the problem you want to solve?

I'd list to use latest docker image tag. The one provided over `quay.io/minio/kes:latest` is one year old.

#### How do you want to solve it?

I'd like to use `quay.io/minio/kes:latest`.

#### Additional context

1. Are there alternative solutions?

Yes, by using specific tag

2. Would your solution cause a major breaking API change?

No

3. Anything else that is important?

No

**Comment by harshavardhana** [comment]
use minio/kes:latest
