### ISSUE TITLE
Cannot connect to kes from minio: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by borremosch** [minio/kes#99]
#### Bug describtion
I have been following the setup of a KES server as per the [instructions for HashiCorp Vault](https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore#kes-server-setup), using a self-signed server certificate. I am trying to connect my Minio instance to KES but I receive an error when attempting to write an object to an encrypted bucket:

```
API: PutObject(bucket=iris-02xsj, object=file.txt)
Time: 10:48:33 UTC 01/14/2021
DeploymentID: 55471ab2-1115-42b6-a2a4-4e53bbfd5846
RequestID: 165A138D116D1D44
RemoteHost: 10.1.155.29
Host: minio
UserAgent: MinIO (linux; x64) minio-js/7.0.16
Error: Post "https://minio-kes:7373/v1/key/generate/minio-key": x509: certificate signed by unknown authority (*url.Error)       4: cmd/api-errors.go:2003:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2028:cmd.toAPIError()
       2: cmd/object-handlers.go:1541:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
```

#### Expected behavior
I expect Minio to connect to KES when using a self-signed certificate, or I would expect the documentation to make some mention of what to do to make this work.

#### Additional context

Using docker images `minio/minio:RELEASE.2021-01-08T21-18-21Z` and `minio/kes:v0.13.1`

**Comment by aead** [comment]
Have you set the following env. variables:
```sh
export MINIO_KMS_KES_ENDPOINT=<endpoint>
export MINIO_KMS_KES_CERT_FILE=<client-certificate>
export MINIO_KMS_KES_KEY_FILE=<client-key>
export MINIO_KMS_KES_CA_PATH=<CA-or-KES-server-certificate>
export MINIO_KMS_KES_KEY_NAME=<key-name>
```
Ref: https://github.com/minio/kes/wiki/MinIO-Object-Storage#minio-configuration

Especially: 
```sh
export MINIO_KMS_KES_CA_PATH=<CA-or-KES-server-certificate>
```
If you use self-signed certificates you may want to use the KES server certificate here directly.

**Comment by borremosch** [comment]
Thank you for the link. Even though I have been working on the KES server for a couple of days now, I did not find this particular page. Perhaps it is a good idea to reference it from the [KMS guide](https://docs.min.io/docs/minio-kms-quickstart-guide.html)?

After adding the `MINIO_KMS_KES_CA_PATH` environment variable, I am now receiving a similar error on the KES (server) side:

```
{"message":"2021/01/14 13:01:56 http: TLS handshake error from 10.1.155.85:46868: tls: failed to verify client certificate: x509: certificate signed by unknown authority"}
```

**Comment by aead** [comment]
> Thank you for the link. Even though I have been working on the KES server for a couple of days now, I did not find this particular page. Perhaps it is a good idea to reference it from the KMS guide?

We are currently in the progress of moving and merging our documentation - e.g. the MinIO S3 Go SDK documentation has  been moved to https://minio-go.min.io - So this may happen eventually. 

> After adding the MINIO_KMS_KES_CA_PATH environment variable, I am now receiving a similar error on the KES (server) side:
> ```
>   {"message":"2021/01/14 13:01:56 http: TLS handshake error from 10.1.155.85:46868: tls: failed to verify client 
>   certificate: x509: certificate signed by unknown authority"}
>```

If you take a look at 5. of the [Hashicorp Vault Guide](https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore) there you can see the following:
> `--auth=off` is required since our root.cert and app.cert certificates are self-signed.

When you want to access a KES server with a TLS client certificate that has not been issued by a CA that is trusted by the KES server then you have to disable the X.509 certificate validation. This analogous to using a self-signed certificate at a server. There, the client has to disable X.509 verification. Since KES uses mutual TLS you have to disable the certificate verification on both ends of the connection.

For more information take a look at: https://github.com/minio/kes/wiki/Concepts#access-control

**Comment by aead** [comment]
Closing this as it seems there is no issue and marking it as answered.

**Comment by colorzzr** [comment]
Hi all! I am also facing this issue. I followed the instruction https://github.com/minio/kes/wiki/MinIO-Object-Storage. Even if I add the `--auth=off` flag, minio still raise the error `x509: certificate signed by unknown authority `. Is there any way to solve this?

**Comment by aead** [comment]
@colorzzr If MinIO raises the error `509: certificate signed by unknown authority` then this means that MinIO does not trust the server certificate of the KES server.

You may want to set `MINIO_KMS_KES_CA_PATH=<path/to/kes-server.crt>` or to the CA that issued the KES server certificate.

See https://github.com/minio/kes/wiki/MinIO-Object-Storage#2-set-the-following-5-minio_kms_kes-environment-variables

> The MinIO server uses MINIO_KMS_KES_CERT_FILE and MINIO_KMS_KES_KEY_FILE to authenticate to KES - similar to the KES CLI above. Further, we have to set MINIO_KMS_KES_CA_PATH since we use self-signed certificates. If you use certificates issued by an internal CA you may want to set MINIO_KMS_KES_CA_PATH to the root certificate of your internal CA instead.

**Comment by schemacs** [comment]
@colorzzr `cp server.cert ~/.minio/certs/CAs/` solves this. @aead No, only setting `MINIO_KMS_KES_CA_PATH` doesn't work.

```
$ minio --version
minio version RELEASE.2021-05-26T00-22-46Z
$  kes --version
kes version 0.14.0
```

**Comment by aead** [comment]
@schemacs Sry, there was a typo:
Set `MINIO_KMS_KES_CAPATH` instead of `MINIO_KMS_KES_CA_PATH`.

The following works for me:
```
export MINIO_KMS_KES_ENDPOINT=https://127.0.0.1:7373
export MINIO_KMS_KES_CERT_FILE=root.cert
export MINIO_KMS_KES_KEY_FILE=root.key
export MINIO_KMS_KES_KEY_NAME=my-key
export MINIO_KMS_KES_CAPATH=kes.crt
```

**Comment by colorzzr** [comment]
@aead @schemacs Thanks! The issue was solved.

**Comment by schemacs** [comment]
@aead Thanks, The [wiki page](https://github.com/minio/kes/wiki/MinIO-Object-Storage#minio-configuration) is correct now.

**Comment by schemacs** [comment]
By the way, regarding with `MINIO_KMS_KES_CERT_FILE` `MINIO_KMS_KES_KEY_FILE` `MINIO_KMS_KES_KEY_NAME` , the incorrect `MINIO_KMS_KES_CA_PATH` is a more reasonable naming.

**Comment by schemacs** [comment]
A little confused, so when in non-containerized environments, we should use `MINIO_KMS_KES_CAPATH`, otherwise (containerized environments) use `MINIO_KMS_KES_CA_PATH`?  https://github.com/minio/minio/pull/9125

**Comment by aead** [comment]
> A little confused, so when in non-containerized environments, we should use MINIO_KMS_KES_CAPATH, otherwise (containerized environments) use MINIO_KMS_KES_CA_PATH

This is outdated information. Today, MinIO uses the KMS to encrypt IAM and config data. Therefore, the KMS config cannot be specified in the config file (chicken-egg-problem). However, I agree that `MINIO_KMS_KES_CA_PATH` is more consistent.

Sent a PR to rename the env. variable. Will update the guide once it has been merged/released.

**Comment by Bubuioc** [comment]
Hello, are there a full good tutorial of how to setup the minio and kes, because I didn't find a good one, even in the docs the certificates generated by kes command when i start kes server it fails with error bad signature.Enyone who successfuly started the minio and kes together please ping.
